services:
  - type: web
    name: university-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: dpg-cva761btq21c73bs7l8g-a.ohio-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: module6_user
      - key: DB_PASSWORD
        value: teuPW5tOTPcuYR1unIobRVxTYDDuZWS5
      - key: DB_NAME
        value: module6